version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable  # Lightweight Linux image with lscpu available
    steps:
      - checkout  # Optional: checks out your repository code
      - run:
          name: Run lscpu
          command: lscpu  # Command to display CPU information

workflows:
  my_workflow:
    jobs:
      - build